### ISSUE TITLE
[BUG] Missing Imports for List and ArrayList 

### ISSUE THREAD

**Issue by rob4abcba** [awkonecki/interview-prep#11]
When try to compile StaticDynamic.java, javac complains "StaticDynamic.java:51: error: cannot find symbol" with the ^ pointing at the "List" and "ArrayList".

**Comment by awkonecki** [comment]
Evidence of [bug](https://github.com/awkonecki/interview-prep/blob/65dd42a80b496db95b2c046224fb8eaf1cc70d89/data-structures/arrays/src/java/StaticDynamic.java#L51)

**Comment by awkonecki** [comment]
Closed by [PR #12](#12)
